<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'delUser' => '删除用户',
  'editUser' => '编辑用户',
  'id:' => '序号:',
  'member' => '用户',
  'operate' => '操作',
  'registerTime' => '注册时间',
  'save' => '保存',
  'update' => '修改',
  'username' => '用户名',
  'email:' => '邮箱:',
  'newUser' => '新建用户',
  'password:' => '密码:',
  'returnUserManage' => '返回用户管理',
  'userManage' => '用户管理',
  'username:' => '用户名:',
);
